-- SEG-03 (T10) — Bitácora append-only con hash encadenado por tenant.
-- RLS ENABLE + FORCE. El rol optisaas_audit_writer solo inserta y lee.
-- optisaas_app solo lee, según la matriz R19. UPDATE, DELETE y TRUNCATE
-- quedan revocados y un trigger los rechaza aunque el dueño insista.
-- No hay columna de contenido clínico. TODO(Q-07): sin plazo de conservación.
CREATE TABLE "auditoria" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tenant_id" uuid NOT NULL REFERENCES "tenants"("id"),
  "ts" timestamptz DEFAULT now() NOT NULL,
  "actor_id" uuid REFERENCES "usuarios"("id"),
  "rol" text,
  "sede_id" uuid REFERENCES "sedes"("id"),
  "recurso" text NOT NULL,
  "recurso_id" text,
  "accion" text NOT NULL,
  "resultado" text NOT NULL,
  "ip" text,
  "agente" text,
  "request_id" text,
  "hash_previo" bytea,
  "hash" bytea NOT NULL,
  CONSTRAINT "auditoria_accion_valida" CHECK ("accion" in (
    'lectura','crear','leer','actualizar','firmar','anular','exportar','solicitar',
    'autenticacion','cambiar_sede','adenda','impresion','descarga','break_glass',
    'configuracion','retencion','cambio_rol'
  )),
  CONSTRAINT "auditoria_resultado_valido" CHECK ("resultado" in ('ok','denegado','error')),
  CONSTRAINT "auditoria_recurso_referencia" CHECK ("recurso" ~ '^[A-Za-z0-9_]{1,40}$'),
  CONSTRAINT "auditoria_rol_referencia" CHECK ("rol" IS NULL OR "rol" ~ '^[a-z_]{1,60}$')
);
--> statement-breakpoint
CREATE INDEX "auditoria_tenant_id_id_idx" ON "auditoria" ("tenant_id", "id");
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'optisaas_audit_writer') THEN
    CREATE ROLE optisaas_audit_writer NOLOGIN;
  END IF;
END $$;
--> statement-breakpoint
REVOKE ALL ON auditoria FROM PUBLIC;
--> statement-breakpoint
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON auditoria FROM optisaas_app;
--> statement-breakpoint
GRANT SELECT ON auditoria TO optisaas_app;
--> statement-breakpoint
GRANT SELECT, INSERT ON auditoria TO optisaas_audit_writer;
--> statement-breakpoint
GRANT USAGE, SELECT ON SEQUENCE auditoria_id_seq TO optisaas_audit_writer;
--> statement-breakpoint
ALTER TABLE auditoria ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE auditoria FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY auditoria_lectura_app ON auditoria FOR SELECT TO optisaas_app
  USING (
    tenant_id::text = current_setting('app.tenant_id', true)
    AND (
      (
        current_setting('app.rol', true) IN ('admin', 'auditor')
        AND (
          sede_id IS NULL
          OR sede_id::text = ANY (string_to_array(coalesce(current_setting('app.sedes', true), ''), ','))
        )
      )
      OR (
        current_setting('app.rol', true) IN ('optometra', 'oftalmologo', 'director_cientifico')
        AND actor_id::text = current_setting('app.usuario_id', true)
        AND sede_id::text = current_setting('app.sede_id', true)
      )
    )
  );
--> statement-breakpoint
CREATE POLICY auditoria_lectura_writer ON auditoria FOR SELECT TO optisaas_audit_writer
  USING (tenant_id::text = current_setting('app.tenant_id', true));
--> statement-breakpoint
CREATE POLICY auditoria_insercion_writer ON auditoria FOR INSERT TO optisaas_audit_writer
  WITH CHECK (tenant_id::text = current_setting('app.tenant_id', true));
--> statement-breakpoint
CREATE OR REPLACE FUNCTION auditoria_rechazar_cambio()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'auditoria es append-only: % prohibido', TG_OP
    USING ERRCODE = '55000';
END;
$$;
--> statement-breakpoint
CREATE TRIGGER auditoria_append_only
  BEFORE UPDATE OR DELETE ON auditoria
  FOR EACH ROW EXECUTE FUNCTION auditoria_rechazar_cambio();
--> statement-breakpoint
CREATE TRIGGER auditoria_append_only_truncate
  BEFORE TRUNCATE ON auditoria
  FOR EACH STATEMENT EXECUTE FUNCTION auditoria_rechazar_cambio();
--> statement-breakpoint
CREATE OR REPLACE FUNCTION ultimo_hash_auditoria(p_tenant uuid)
RETURNS bytea
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  ultimo bytea;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtextextended(p_tenant::text, 0));
  SELECT a.hash INTO ultimo
    FROM auditoria a
   WHERE a.tenant_id = p_tenant
   ORDER BY a.id DESC
   LIMIT 1;
  RETURN ultimo;
END;
$$;
--> statement-breakpoint
CREATE OR REPLACE FUNCTION registrar_fila_auditoria(
  p_tenant uuid,
  p_ts timestamptz,
  p_actor uuid,
  p_rol text,
  p_sede uuid,
  p_recurso text,
  p_recurso_id text,
  p_accion text,
  p_resultado text,
  p_ip text,
  p_agente text,
  p_request_id text,
  p_hash_previo bytea,
  p_hash bytea
) RETURNS bigint
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  ultimo bytea;
  nuevo bigint;
BEGIN
  IF current_user <> 'optisaas_audit_writer' THEN
    RAISE EXCEPTION 'la insercion de auditoria exige optisaas_audit_writer';
  END IF;
  IF p_hash IS NULL OR octet_length(p_hash) <> 32 THEN
    RAISE EXCEPTION 'hash de auditoria invalido';
  END IF;
  IF p_hash_previo IS NOT NULL AND octet_length(p_hash_previo) <> 32 THEN
    RAISE EXCEPTION 'hash previo de auditoria invalido';
  END IF;
  PERFORM pg_advisory_xact_lock(hashtextextended(p_tenant::text, 0));
  SELECT a.hash INTO ultimo
    FROM auditoria a
   WHERE a.tenant_id = p_tenant
   ORDER BY a.id DESC
   LIMIT 1;
  IF ultimo IS DISTINCT FROM p_hash_previo THEN
    RAISE EXCEPTION 'cadena de auditoria desfasada';
  END IF;
  PERFORM set_config('app.tenant_id', p_tenant::text, true);
  INSERT INTO auditoria (
    tenant_id, ts, actor_id, rol, sede_id, recurso, recurso_id,
    accion, resultado, ip, agente, request_id, hash_previo, hash
  ) VALUES (
    p_tenant, p_ts, p_actor, p_rol, p_sede, p_recurso, p_recurso_id,
    p_accion, p_resultado, p_ip, p_agente, p_request_id, p_hash_previo, p_hash
  )
  RETURNING id INTO nuevo;
  RETURN nuevo;
END;
$$;
--> statement-breakpoint
REVOKE ALL ON FUNCTION ultimo_hash_auditoria(uuid) FROM PUBLIC;
--> statement-breakpoint
REVOKE ALL ON FUNCTION registrar_fila_auditoria(uuid, timestamptz, uuid, text, uuid, text, text, text, text, text, text, text, bytea, bytea) FROM PUBLIC;
--> statement-breakpoint
GRANT optisaas_audit_writer TO optisaas_app WITH INHERIT FALSE;
--> statement-breakpoint
GRANT EXECUTE ON FUNCTION ultimo_hash_auditoria(uuid) TO optisaas_app;
--> statement-breakpoint
GRANT EXECUTE ON FUNCTION registrar_fila_auditoria(uuid, timestamptz, uuid, text, uuid, text, text, text, text, text, text, text, bytea, bytea) TO optisaas_audit_writer;
